---
_java_package:
  oracle:
    jre:
      8:
        targz: jre-8u191-linux-x64.tar.gz
        rpm: jre-8u191-linux-x64.rpm
        directory: jre1.8.0_191
      10:
        targz: jre-10.0.2_linux-x64_bin.tar.gz
        rpm: jre-10.0.2_linux-x64_bin.rpm
        directory: jre-10.0.2
    jdk:
      8:
        targz: jdk-8u191-linux-x64.tar.gz
        rpm: jdk-8u191-linux-x64.rpm
        directory: jdk1.8.0_191
      10:
        targz: jdk-10.0.2_linux-x64_bin.tar.gz
        rpm: jdk-10.0.2_linux-x64_bin.rpm
        directory: jdk-10.0.2

java_oracle_package: "{{ _java_oracle_package[java_type][java_version][java_format] | default([]) }}"

java_oracle_directory: "{{ _java_oracle_package[java_type][java_version]['directory] }}"

jce_download_url: "http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html?ssSourceSiteId=otnpt"
